### Updates an existing patient entity
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174001
Content-Type: application/json

{

  "name": "Johnathan Doe UPDATED",
  "email": "john@example.com",
  "address": "123 Main St, Springfield",
  "dateOfBirth": "1985-06-15"
}

###